---
title: "inspecting output data"
author: "Olivia Cattau"
date: "10/21/2021"
output: html_document
---

```{r}
countMatrix<-read.table(file="/Users/oliviacattau/Documents/data/abundance_10.21.21.tsv", header=TRUE)
head(countMatrix)
```

```{r}
blast_data<-read.table(file="https://gannet.fish.washington.edu/gigas/Panopea-generosa-uniprot_blastx.tab")
names(blast_data)[1]<-"target_id" #renamed to match countMATRIX data
names(blast_data)[2]<-"identifiers" #renamed to search in swiss prot 
library("writexl")
write_xlsx(identifiers,"\\Users\\oliviacattau\\Documents\\data\\filename.xlsx")
```

```{r}
library(dplyr)
library(tidyr)
#merging target_ids to count Matrix to get identifies for swiss prot
generosa_counts<-full_join(blast_data, countMatrix, by = "target_id")
generosa_counts<-generosa_counts[-c(3:12)] # not every target ID has a protein identifier...could be an issue later on....
generosa_counts[complete.cases(generosa_counts),]
#blast_data<-read.csv(file="/Users/oliviacattau/Documents/analysis/code/generosa_counts.csv")#lost count data due to excel stupidity
generosa_counts$identifiers<-sub("\\.\\d+$", "", generosa_counts$identifiers)
cols_to_check = 2
print (generosa_counts[cols_to_check])
```

```{r}
#load uniprot output from excel
names(uniprot_proteins_11_8_21)[1]<-"identifiers" #renamed
generosa_proteins<-full_join(generosa_counts, uniprot_proteins_11_8_21, by ="identifiers")
#make file smaller before exporting later 
#tpm=Transcripts Per Kilobase Million
library(openxlsx)
write.csv(generosa_proteins_11_8_21, file = "\\Users\\oliviacattau\\Documents\\data\\generosa_counts_proteins.csv")
pgenerosa_wb<-
```

```{r}
attach(generosa_proteins)
vector<-numeric(length=length(generosa_proteins$est_counts))
for (i in seq_along(generosa_proteins$est_counts)) {
  vector[i] <- generosa_proteins$est_counts[i] >=10
}
head(vector)
```
